name: EquipmentListener
version: '${project.version}'
api-version: 1.19
main: com.senrua.equipmentlistener.EquipmentListener
author: Rainie
description: Patches Aurelium Skills & MMOItems confliction Health Bug
commands:
